baseURL: "https://evgnomon.org/"
title: Hamed Ghasemzadeh

pagination:
  pagerSize: 10
theme: etch

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  description: "Hamed Ghasemzadeh"
  subtitle: "Freedom 🦄 is not an option for you unless being your choice."
  author:
    name: evgnomon
    email: hg@evgnomon.org
  mainSections: [posts]
  dark: auto # auto, on, off
  highlight: true
  googleSiteVerification: "G-DQ3YB70298"
  socialIcons:
    - name: GitHub
      url: "https://github.com/evgnomon"
    - name: Email
      url: "mailto:hg@evgnomon.org"
    - name: RSS
      url: "https://evgnomon.org/posts/index.xml"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/evgnomon/"
    - name: X
      url: "https://x.com/evgnomon"
    - name: Nostr
      url: "https://primal.net/p/npub1tkehxccwdxqhu3gt6fk33ykznd7ad9aa2p58s95lpnx3mznu6kjqk65725"

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
outputs:
  home:
    - HTML
    - RSS
    - JSON

defaultContentLanguage: en
languages:
  en:
    languageName: English
    languageCode: en-us
    weight: 1
    menu:
      main:
        - identifier: tags-pages
          name: Tags
          url: /tags/
          weight: 20
        - identifier: search-page
          name: Search
          url: /search/
          weight: 30
        - identifier: hgl
          name: HGL
          url: /docs/hgl
          weight: 31
        - identifier: openpgp-page
          name: OpenPGP
          url: /docs/openpgp
          weight: 34
        - identifier: about-page
          name: About
          url: /docs/about
          weight: 40
        - identifier: usecode-github
          name: Usecode
          url: https://github.com/evgnomon/usecode
          weight: 50
